### PR TITLE
Make the R part of case 20 run

### PR DESCRIPTION
**Pull request by chainsawriot**
1_prepare_data.R won't run, as written in the R script that the raw ALM data can't be shared.

### CODE REVIEW

**Comment by JBGruber** [comment]
The sh file mentions a `2.diff`, which I do not have :(

**Comment by chainsawriot** [comment]
@JBGruber Here we go. Sorry for missing that.

**Comment by JBGruber** [comment]
Cheers! I'm now fiddling with the docker file included in the repo. It doesn't build though because of an issue with the cuda drivers (surprise).

**Comment by JBGruber** [comment]
I solved the driver issue but now I'm hit with:

```
make[2]: *** No rule to make target '/usr/local/cuda/lib64/libnvcuvid.so', needed by 'libdecord.so'.  Stop.
```

Even though `libnvcuvid.so` should be in the right location already.

**Comment by JBGruber** [comment]
As mentioned in https://github.com/Kudusch/reprohack23/issues/35, I managed to build the Dockerfile, but a shell script is missing, making this impossible to reproduce. I'm committing the code as far as I got anyway.

**Pull request merged**
